export const GET_QUESTIONS = "GET_QUESTIONS"
export const ADD_QUESTION = "ADD_QUESTION"
export const DELETE_QUESTION = "DELETE_QUESTION"
export const QUESTIONS_LOADING = "QUESTIONS_LOADING"

export const GET_QUESTIONSFORMS = "GET_QUESTIONSFORMS"
export const ADD_QUESTIONSFORM = "ADD_QUESTIONSFORM"
export const DELETE_QUESTIONSFORM = "DELETE_QUESTIONSFORM"
export const QUESTIONSFORMS_LOADING = "QUESTIONSFORMS_LOADING"